<?php

namespace App\Enums;

enum TransactionEnum
{
    case DEBIT;

    case CREDIT;

    case TRANSFER_POINT_TO_USER;

    case POS_CREATING_CARDS;

    case AGENT_CREATING_CARDS;

    case CREDIT_USER_BY_CHARGING_CARD;

    case CREDIT_USER_DUE_COMPLETE_ORDER;

    case CREDIT_SELLER_BY_CHARGING_CARD;

    case CREDIT_SHIPPING_COMPANY_BY_CHARGING_CARD;

    case CARD_ORDER;

    case TRANSFER_POINTS_DUE_TO_COMPLETE_ORDER;

    case TRANSFER_POINT_TO_SELLER;

    case TRANSFER_POINT_TO_POS;

    case TRANSFER_POINT_TO_AGENT;

    case SELLER_SUBSCRIPTION;

    case SELLER_SEND_NOTIFICATION_SERVICE;

    case SELLER_ADD_PRODUCT_TO_SLIDER;

    case SELLER_ADD_BLUE_TAG;

    case SELLER_ADD_PRODUCT_TO_OFFER;

    case RETRIEVE;

    case SELLER_UPLOAD_PRODUCT;

    case COMPLETED_GIFT_ORDER;

    case WITHDRAWAL;
}
